// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/spf13/pflag"
	"velda.io/velda/pkg/broker"
	"velda.io/velda/pkg/proto"

	_ "net/http/pprof"

	_ "velda.io/velda/pkg/broker/backends/registry"
)

// Injectors from wire.go:

func RunAllService(flag *pflag.FlagSet) (CompletionError, error) {
	serverMetrics := ProvideGrpcMetrics()
	configPath := ProvideConfigPath(flag)
	config, err := ProvideConfig(configPath)
	if err != nil {
		return nil, err
	}
	mtlsMethodSPIFFEMap := ProvideMTLSMethodSPIFFEMap(config)
	apiserverMtlsVerifier := ProvideMTLSVerifier(mtlsMethodSPIFFEMap)
	serverMtlsUnaryInterceptor := ProvideMTLSUnaryInterceptor(apiserverMtlsVerifier)
	serverMtlsStreamInterceptor := ProvideMTLSStreamInterceptor(apiserverMtlsVerifier)
	serverAuthUnaryInterceptor := _wireServerAuthUnaryInterceptorValue
	serverAuthStreamInterceptor := _wireServerAuthStreamInterceptorValue
	server := ProvideGrpcServer(serverMetrics, serverMtlsUnaryInterceptor, serverMtlsStreamInterceptor, serverAuthUnaryInterceptor, serverAuthStreamInterceptor)
	serveMux := ProvideHttpHandler()
	runtimeServeMux := ProvideGrpcMux(serveMux)
	serviceCtx := ProvideBaseCtx()
	context := ProvideCtx(serviceCtx)
	brokerInfo := ProvideBrokerInfo(context, config)
	schedulerSet, err := ProvideSchedulers(context, config, brokerInfo)
	if err != nil {
		return nil, err
	}
	sessionCompletionWatcher := _wireNullCompletionWatcherValue
	watcher := broker.NewWatcher()
	quotaChecker := ProvideQuotaChecker()
	sessionHelper := ProvideSessionHelper(sessionCompletionWatcher, watcher, quotaChecker)
	sessionDatabase := broker.NewSessionDatabase(sessionHelper)
	permissions := ProvidePermission()
	storage, err := ProvideStorage(config)
	if err != nil {
		return nil, err
	}
	apiserverDatabase, err := ProvideDb(storage, context)
	if err != nil {
		return nil, err
	}
	provisionRunner, err := ProvideProvisioners(context, config, schedulerSet, brokerInfo)
	if err != nil {
		return nil, err
	}
	regionId := ProvideRegionId()
	taskTracker := ProvideTaskTracker(config, context, schedulerSet, sessionDatabase, apiserverDatabase, provisionRunner, watcher, regionId, storage)
	localDiskProvider := ProvideLocalDiskStorage(storage)
	serverIP, err := ProvideNfsServer(config)
	if err != nil {
		return nil, err
	}
	localNfsAuth, err := ProvideLocalNfsAuth(localDiskProvider, serverIP)
	if err != nil {
		return nil, err
	}
	brokerAuth := NewBrokerAuth(localNfsAuth)
	storageManager := ProvideStorageManager(storage)
	brokerServiceServer := ProvideBrokerServer(server, runtimeServeMux, schedulerSet, sessionDatabase, permissions, taskTracker, brokerAuth, apiserverDatabase, storageManager)
	taskLogDb := ProvideTaskLogDb(config, storage)
	taskServiceServer := ProvideTaskService(context, server, runtimeServeMux, apiserverDatabase, taskLogDb, taskTracker, permissions)
	poolManagerServiceServer := ProvidePoolService(context, server, runtimeServeMux, schedulerSet)
	instanceServiceServer := ProvideInstanceService(server, runtimeServeMux, apiserverDatabase, storage, permissions, brokerServiceServer)
	taskLogServiceServer := ProvideTaskLogService(server, config)
	registry := _wireRegistryValue
	metricRegistryRunner := ProvideMetrics(registry, serverMetrics, schedulerSet)
	grpcRunner, err := ProvideGrpcRunner(serviceCtx, config, server)
	if err != nil {
		return nil, err
	}
	httpRunner, err := ProvideHttpRunner(serviceCtx, config, serveMux)
	if err != nil {
		return nil, err
	}
	readyFd := ProvideReadyFd(flag)
	readySignalRunner := ProvideReadySignal(readyFd)
	v := ProvideRunners(brokerServiceServer, taskServiceServer, poolManagerServiceServer, instanceServiceServer, taskLogServiceServer, metricRegistryRunner, provisionRunner, grpcRunner, httpRunner, readySignalRunner)
	completionError := ProvideCompletionSignal(v, serviceCtx)
	return completionError, nil
}

var (
	_wireServerAuthUnaryInterceptorValue  = ServerAuthUnaryInterceptor(sessionInterceptor)
	_wireServerAuthStreamInterceptorValue = ServerAuthStreamInterceptor(sessionStreamInterceptor)
	_wireNullCompletionWatcherValue       = &broker.NullCompletionWatcher{}
	_wireRegistryValue                    = AllMetrics
)

// wire.go:

func ProvideRunners(
	_ proto.BrokerServiceServer,
	_ proto.TaskServiceServer,
	_ proto.PoolManagerServiceServer,
	_ proto.InstanceServiceServer,
	_ proto.TaskLogServiceServer,
	metrics MetricRegistryRunner,
	provisioners ProvisionRunner,
	grpcRunner GrpcRunner,
	httpRunner HttpRunner,
	ready ReadySignalRunner,
) []Runner {
	return []Runner{
		Runner(metrics),
		Runner(provisioners),
		Runner(httpRunner),
		Runner(grpcRunner),
		Runner(ready),
	}
}
