// Copyright 2025 Velda Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentDaemon_Mount_FullMethodName      = "/velda.AgentDaemon/Mount"
	AgentDaemon_CheckPoint_FullMethodName = "/velda.AgentDaemon/CheckPoint"
)

// AgentDaemonClient is the client API for AgentDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentDaemonClient interface {
	Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CheckPoint(ctx context.Context, in *CheckPointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type agentDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentDaemonClient(cc grpc.ClientConnInterface) AgentDaemonClient {
	return &agentDaemonClient{cc}
}

func (c *agentDaemonClient) Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentDaemon_Mount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentDaemonClient) CheckPoint(ctx context.Context, in *CheckPointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentDaemon_CheckPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentDaemonServer is the server API for AgentDaemon service.
// All implementations must embed UnimplementedAgentDaemonServer
// for forward compatibility.
type AgentDaemonServer interface {
	Mount(context.Context, *MountRequest) (*emptypb.Empty, error)
	CheckPoint(context.Context, *CheckPointRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAgentDaemonServer()
}

// UnimplementedAgentDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentDaemonServer struct{}

func (UnimplementedAgentDaemonServer) Mount(context.Context, *MountRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mount not implemented")
}
func (UnimplementedAgentDaemonServer) CheckPoint(context.Context, *CheckPointRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPoint not implemented")
}
func (UnimplementedAgentDaemonServer) mustEmbedUnimplementedAgentDaemonServer() {}
func (UnimplementedAgentDaemonServer) testEmbeddedByValue()                     {}

// UnsafeAgentDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentDaemonServer will
// result in compilation errors.
type UnsafeAgentDaemonServer interface {
	mustEmbedUnimplementedAgentDaemonServer()
}

func RegisterAgentDaemonServer(s grpc.ServiceRegistrar, srv AgentDaemonServer) {
	// If the following call pancis, it indicates UnimplementedAgentDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentDaemon_ServiceDesc, srv)
}

func _AgentDaemon_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentDaemonServer).Mount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentDaemon_Mount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentDaemonServer).Mount(ctx, req.(*MountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentDaemon_CheckPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentDaemonServer).CheckPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentDaemon_CheckPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentDaemonServer).CheckPoint(ctx, req.(*CheckPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentDaemon_ServiceDesc is the grpc.ServiceDesc for AgentDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "velda.AgentDaemon",
	HandlerType: (*AgentDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mount",
			Handler:    _AgentDaemon_Mount_Handler,
		},
		{
			MethodName: "CheckPoint",
			Handler:    _AgentDaemon_CheckPoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
