// Copyright 2025 Velda Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: execution.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workload_ShardScheduling int32

const (
	// Default to standard
	Workload_SHARD_SCHEDULING_UNSPECIFIED Workload_ShardScheduling = 0
	// Each shard is scheduled independently.
	Workload_SHARD_SCHEDULING_STANDARD Workload_ShardScheduling = 1
	// All shards are scheduled together.
	Workload_SHARD_SCHEDULING_GANG Workload_ShardScheduling = 2
)

// Enum value maps for Workload_ShardScheduling.
var (
	Workload_ShardScheduling_name = map[int32]string{
		0: "SHARD_SCHEDULING_UNSPECIFIED",
		1: "SHARD_SCHEDULING_STANDARD",
		2: "SHARD_SCHEDULING_GANG",
	}
	Workload_ShardScheduling_value = map[string]int32{
		"SHARD_SCHEDULING_UNSPECIFIED": 0,
		"SHARD_SCHEDULING_STANDARD":    1,
		"SHARD_SCHEDULING_GANG":        2,
	}
)

func (x Workload_ShardScheduling) Enum() *Workload_ShardScheduling {
	p := new(Workload_ShardScheduling)
	*p = x
	return p
}

func (x Workload_ShardScheduling) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Workload_ShardScheduling) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_proto_enumTypes[0].Descriptor()
}

func (Workload_ShardScheduling) Type() protoreflect.EnumType {
	return &file_execution_proto_enumTypes[0]
}

func (x Workload_ShardScheduling) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Workload_ShardScheduling.Descriptor instead.
func (Workload_ShardScheduling) EnumDescriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0, 0}
}

type Workload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The binary path to execute.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// If provided, the absolute path to the binary.
	CommandPath string `protobuf:"bytes,9,opt,name=command_path,json=commandPath,proto3" json:"command_path,omitempty"`
	// The arguments to pass to the binary.
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// The working directory to execute the command in.
	// If empty, home directory will be used.
	WorkingDir string `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// The environment variables to set for the command.
	// Environment variables are passed in the form of key=value.
	Environs []string `protobuf:"bytes,4,rep,name=environs,proto3" json:"environs,omitempty"`
	// Whether to execute the command in a shell.
	// If true, command will be the shell script and args are ignored.
	// If command is empty, it will start the default shell at current directory.
	Shell bool `protobuf:"varint,5,opt,name=shell,proto3" json:"shell,omitempty"`
	// The system user credentials to execute the command.
	Uid    uint32   `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid    uint32   `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`
	Groups []uint32 `protobuf:"varint,8,rep,packed,name=groups,proto3" json:"groups,omitempty"`
	// Total number of shards.
	TotalShards     int32                    `protobuf:"varint,10,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	ShardScheduling Workload_ShardScheduling `protobuf:"varint,11,opt,name=shard_scheduling,json=shardScheduling,proto3,enum=velda.Workload_ShardScheduling" json:"shard_scheduling,omitempty"`
	// 0-based index of the current shard.
	// -1 is used for parent group.
	ShardIndex    int32 `protobuf:"varint,12,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

func (x *Workload) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Workload) GetCommandPath() string {
	if x != nil {
		return x.CommandPath
	}
	return ""
}

func (x *Workload) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Workload) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *Workload) GetEnvirons() []string {
	if x != nil {
		return x.Environs
	}
	return nil
}

func (x *Workload) GetShell() bool {
	if x != nil {
		return x.Shell
	}
	return false
}

func (x *Workload) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Workload) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Workload) GetGroups() []uint32 {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Workload) GetTotalShards() int32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

func (x *Workload) GetShardScheduling() Workload_ShardScheduling {
	if x != nil {
		return x.ShardScheduling
	}
	return Workload_SHARD_SCHEDULING_UNSPECIFIED
}

func (x *Workload) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

type BatchTaskResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExitCode         *int32                 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	TerminatedSignal int32                  `protobuf:"varint,2,opt,name=terminated_signal,json=terminatedSignal,proto3" json:"terminated_signal,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchTaskResult) Reset() {
	*x = BatchTaskResult{}
	mi := &file_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTaskResult) ProtoMessage() {}

func (x *BatchTaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTaskResult.ProtoReflect.Descriptor instead.
func (*BatchTaskResult) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

func (x *BatchTaskResult) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *BatchTaskResult) GetTerminatedSignal() int32 {
	if x != nil {
		return x.TerminatedSignal
	}
	return 0
}

var File_execution_proto protoreflect.FileDescriptor

var file_execution_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x76, 0x65, 0x6c, 0x64, 0x61, 0x22, 0xe9, 0x03, 0x0a, 0x08, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e,
	0x67, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x64, 0x73, 0x12, 0x4a, 0x0a, 0x10, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x76, 0x65, 0x6c, 0x64, 0x61, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x69, 0x6e, 0x67, 0x52, 0x0f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x6d, 0x0a, 0x0f, 0x53, 0x68, 0x61, 0x72, 0x64, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x1c, 0x53, 0x48, 0x41, 0x52,
	0x44, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x48,
	0x41, 0x52, 0x44, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x53,
	0x54, 0x41, 0x4e, 0x44, 0x41, 0x52, 0x44, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x48, 0x41,
	0x52, 0x44, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x47, 0x41,
	0x4e, 0x47, 0x10, 0x02, 0x22, 0x6e, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78,
	0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x78, 0x69, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x76, 0x65, 0x6c, 0x64, 0x61, 0x2e, 0x69, 0x6f,
	0x2f, 0x76, 0x65, 0x6c, 0x64, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_execution_proto_rawDescOnce sync.Once
	file_execution_proto_rawDescData = file_execution_proto_rawDesc
)

func file_execution_proto_rawDescGZIP() []byte {
	file_execution_proto_rawDescOnce.Do(func() {
		file_execution_proto_rawDescData = protoimpl.X.CompressGZIP(file_execution_proto_rawDescData)
	})
	return file_execution_proto_rawDescData
}

var file_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_execution_proto_goTypes = []any{
	(Workload_ShardScheduling)(0), // 0: velda.Workload.ShardScheduling
	(*Workload)(nil),              // 1: velda.Workload
	(*BatchTaskResult)(nil),       // 2: velda.BatchTaskResult
}
var file_execution_proto_depIdxs = []int32{
	0, // 0: velda.Workload.shard_scheduling:type_name -> velda.Workload.ShardScheduling
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_execution_proto_init() }
func file_execution_proto_init() {
	if File_execution_proto != nil {
		return
	}
	file_execution_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_execution_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_execution_proto_goTypes,
		DependencyIndexes: file_execution_proto_depIdxs,
		EnumInfos:         file_execution_proto_enumTypes,
		MessageInfos:      file_execution_proto_msgTypes,
	}.Build()
	File_execution_proto = out.File
	file_execution_proto_rawDesc = nil
	file_execution_proto_goTypes = nil
	file_execution_proto_depIdxs = nil
}
