// Copyright 2025 Velda Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: export_config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExportConfig is the schema for the /.dockerexports YAML config file used
// by `velda instance export`. It controls which files are packed into the
// container image and allows composing multiple configs together.
type ExportConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// include lists local file paths or HTTPS URLs to other ExportConfig YAML
	// files that should be merged into this config. Included configs are
	// resolved and merged first (in declaration order); the current config's
	// settings are applied on top. Cycles are detected and ignored.
	Include []string `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	// exclude lists glob patterns (relative to "/", no leading slash) for paths
	// that should be omitted from the packed image layer.
	// Patterns follow Go's path.Match syntax, e.g.:
	//   - "tmp/*"             matches everything directly under /tmp
	//   - "home/user/.cache"  matches that exact path
	//   - "**"               is NOT supported; use a directory prefix instead
	Exclude       []string `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportConfig) Reset() {
	*x = ExportConfig{}
	mi := &file_export_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportConfig) ProtoMessage() {}

func (x *ExportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_export_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportConfig.ProtoReflect.Descriptor instead.
func (*ExportConfig) Descriptor() ([]byte, []int) {
	return file_export_config_proto_rawDescGZIP(), []int{0}
}

func (x *ExportConfig) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *ExportConfig) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

var File_export_config_proto protoreflect.FileDescriptor

var file_export_config_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x65, 0x6c, 0x64, 0x61, 0x22, 0x42, 0x0a, 0x0c,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x69,
	0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65,
	0x42, 0x1a, 0x5a, 0x18, 0x76, 0x65, 0x6c, 0x64, 0x61, 0x2e, 0x69, 0x6f, 0x2f, 0x76, 0x65, 0x6c,
	0x64, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_export_config_proto_rawDescOnce sync.Once
	file_export_config_proto_rawDescData = file_export_config_proto_rawDesc
)

func file_export_config_proto_rawDescGZIP() []byte {
	file_export_config_proto_rawDescOnce.Do(func() {
		file_export_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_export_config_proto_rawDescData)
	})
	return file_export_config_proto_rawDescData
}

var file_export_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_export_config_proto_goTypes = []any{
	(*ExportConfig)(nil), // 0: velda.ExportConfig
}
var file_export_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_export_config_proto_init() }
func file_export_config_proto_init() {
	if File_export_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_export_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_export_config_proto_goTypes,
		DependencyIndexes: file_export_config_proto_depIdxs,
		MessageInfos:      file_export_config_proto_msgTypes,
	}.Build()
	File_export_config_proto = out.File
	file_export_config_proto_rawDesc = nil
	file_export_config_proto_goTypes = nil
	file_export_config_proto_depIdxs = nil
}
