// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pools.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoolManagerService_ListPools_FullMethodName = "/velda.PoolManagerService/ListPools"
)

// PoolManagerServiceClient is the client API for PoolManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoolManagerServiceClient interface {
	ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error)
}

type poolManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolManagerServiceClient(cc grpc.ClientConnInterface) PoolManagerServiceClient {
	return &poolManagerServiceClient{cc}
}

func (c *poolManagerServiceClient) ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoolsResponse)
	err := c.cc.Invoke(ctx, PoolManagerService_ListPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolManagerServiceServer is the server API for PoolManagerService service.
// All implementations must embed UnimplementedPoolManagerServiceServer
// for forward compatibility.
type PoolManagerServiceServer interface {
	ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error)
	mustEmbedUnimplementedPoolManagerServiceServer()
}

// UnimplementedPoolManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolManagerServiceServer struct{}

func (UnimplementedPoolManagerServiceServer) ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPools not implemented")
}
func (UnimplementedPoolManagerServiceServer) mustEmbedUnimplementedPoolManagerServiceServer() {}
func (UnimplementedPoolManagerServiceServer) testEmbeddedByValue()                            {}

// UnsafePoolManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolManagerServiceServer will
// result in compilation errors.
type UnsafePoolManagerServiceServer interface {
	mustEmbedUnimplementedPoolManagerServiceServer()
}

func RegisterPoolManagerServiceServer(s grpc.ServiceRegistrar, srv PoolManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPoolManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolManagerService_ServiceDesc, srv)
}

func _PoolManagerService_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolManagerServiceServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolManagerService_ListPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolManagerServiceServer).ListPools(ctx, req.(*ListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoolManagerService_ServiceDesc is the grpc.ServiceDesc for PoolManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "velda.PoolManagerService",
	HandlerType: (*PoolManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPools",
			Handler:    _PoolManagerService_ListPools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pools.proto",
}
