name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
      - 'release/*'

jobs:
  pr-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run make
        run: make

      - name: Run unit tests
        run: make unittest
